services:
    uam_i18n.twig:
        class: UAM\Twig\Extension\I18n\I18nExtension
        tags:
            - { name: twig.extension }

    twig.extension.period:
        class: UAM\Twig\Extension\I18n\PeriodExtension
        arguments: ["@translator"]
        tags:
            - { name: twig.extension }

    twig.duration.extension:
        class: UAM\Twig\Extension\I18n\DurationExtension
        arguments: ["@translator"]
        tags:
            - { name: twig.extension }
